# Generated by Django 4.2 on 2023-04-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(
                default="", upload_to="", verbose_name="Documento anexado"
            ),
            preserve_default=False,
        ),
    ]
