# Generated by Django 4.2 on 2023-04-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_document_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="file",
            new_name="raw_file_data",
        ),
        migrations.AlterField(
            model_name="document",
            name="document_file",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Documento anexado"
            ),
        ),
    ]
