# Generated by Django 4.2 on 2023-04-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_remove_document_raw_file_data_document_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file",
        ),
        migrations.AlterField(
            model_name="document",
            name="document_file",
            field=models.FileField(
                default="", upload_to="", verbose_name="Documento anexado"
            ),
            preserve_default=False,
        ),
    ]
