# Generated by Django 4.2 on 2023-04-09 03:31

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dateCreated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "lastModified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificacao"
                    ),
                ),
                ("isActive", models.BooleanField(default=True, null=True)),
                ("isPublic", models.BooleanField(default=False, null=True)),
                ("isRemoved", models.BooleanField(default=False, null=True)),
                ("answer_content", models.TextField(verbose_name="Resposta")),
            ],
            options={
                "verbose_name": "Resposta",
                "verbose_name_plural": "Respostas",
                "ordering": ["lastModified"],
                "abstract": False,
            },
            bases=(models.Model, project.models.BaseModelForeignMixin),
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dateCreated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "lastModified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificacao"
                    ),
                ),
                ("isActive", models.BooleanField(default=True, null=True)),
                ("isPublic", models.BooleanField(default=False, null=True)),
                ("isRemoved", models.BooleanField(default=False, null=True)),
                (
                    "prompt_name",
                    models.CharField(max_length=128, verbose_name="Nome do prompt"),
                ),
            ],
            options={
                "verbose_name": "Prompts",
                "verbose_name_plural": "Prompts",
                "ordering": ["lastModified"],
                "abstract": False,
            },
            bases=(models.Model, project.models.BaseModelForeignMixin),
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dateCreated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "lastModified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificacao"
                    ),
                ),
                ("isActive", models.BooleanField(default=True, null=True)),
                ("isPublic", models.BooleanField(default=False, null=True)),
                ("isRemoved", models.BooleanField(default=False, null=True)),
                (
                    "template_name",
                    models.CharField(max_length=128, verbose_name="Nome do template"),
                ),
                (
                    "template_file",
                    models.FileField(upload_to="", verbose_name="Template"),
                ),
            ],
            options={
                "verbose_name": "Template do Chat",
                "verbose_name_plural": "Templates dos Chats",
                "ordering": ["lastModified"],
                "abstract": False,
            },
            bases=(models.Model, project.models.BaseModelForeignMixin),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dateCreated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "lastModified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificacao"
                    ),
                ),
                ("isActive", models.BooleanField(default=True, null=True)),
                ("isPublic", models.BooleanField(default=False, null=True)),
                ("isRemoved", models.BooleanField(default=False, null=True)),
                ("question_content", models.TextField(verbose_name="Pergunta")),
                (
                    "answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answer_questions",
                        to="chats.answer",
                        verbose_name="Resposta",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_questions",
                        to="chats.prompt",
                        verbose_name="ChatGPT prompt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questions",
                "verbose_name_plural": "Questions",
                "ordering": ["lastModified"],
                "abstract": False,
            },
            bases=(models.Model, project.models.BaseModelForeignMixin),
        ),
    ]
