# Generated by Django 4.2 on 2023-04-09 03:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["lastModified"],
                "verbose_name": "Pergunta",
                "verbose_name_plural": "Perguntas",
            },
        ),
    ]
