# Generated by Django 4.2 on 2023-04-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0002_question_isready"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="generated_embedding",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="question",
            name="num_tokens",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Total de tokens"
            ),
        ),
    ]
