# Generated by Django 4.2 on 2023-04-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0003_question_generated_embedding_question_num_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="generated_embedding",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
