# Generated by Django 4.2 on 2023-04-12 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0004_alter_question_generated_embedding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="answer",
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="answers_for_this_question",
                to="chats.question",
                verbose_name="Pergunta",
            ),
        ),
    ]
