from django.urls import path, include, re_path
from accounts.views import (
    AccountTypeTemplateView,
    AccountTypeDetailView,
    AccountTypeListView,
    AccountTypeUpdateView,
    AccountTypeDeleteView,
    AccountTypeCreateView,
)

urlpatterns = [
    path(
        "",
        AccountTypeTemplateView.as_view(
            template_name="accounttype/app_templates/v1/accounttype_index.html"
        ),
        name="accounttype-index",
    ),
    path(
        "collection/",
        AccountTypeListView.as_view(
            template_name="accounttype/app_templates/v1/accounttype_list.html"
        ),
        name="accounttype-list",
    ),
    path(
        "collection/<int:pk>/",
        AccountTypeDetailView.as_view(
            template_name="accounttype/app_templates/v1/accounttype_detail.html"
        ),
        name="accounttype-detail",
    ),
    path(
        "collection/<int:pk>/editar/",
        AccountTypeUpdateView.as_view(
            template_name="accounttype/app_templates/v1/accounttype_update.html"
        ),
        name="accounttype-update",
    ),
    path(
        "collection/<int:pk>/remover/",
        AccountTypeDeleteView.as_view(
            template_name="accounttype/app_templates/v1/accounttype_delete.html"
        ),
        name="accounttype-delete",
    ),
    path(
        "collection/adicionar/",
        AccountTypeCreateView.as_view(
            template_name="accounttype/app_templates/v1/accounttype_create.html"
        ),
        name="accounttype-create",
    ),
]
